### PR TITLE
(feat) Docker Image

### PR DESCRIPTION
**Pull request by angelosarto**
This PR creates a ready-to-use docker container for postgraphql.   It is a minimal docker container based on the generic 'node:alpine' image.  The Alpine linux version was used here to make the resulting image smaller (the standard node image is 265MB, alpine is is 22MB).  Including postgraphql and dependencies the total image is 102MB.

I have added instructions to the readme on how to retrieve the image from docker hub as well as how to run it.  Basically you pass the postgraphql command line options to the docker image the same as if you were running it locally.   It does not include postgres as this is meant to be a standalone, ready-to-use production container of postgraphql.
(I will create some examples of how to run it along with a dockerized postgres in a later PR to either the documentation site and/or to the examples/doc folders.)

Dockerhub will store the docker image for people to retrieve the pre-built postgraphql image.  I have created an account named postgraphql that will own the postgraphql image.  In order to setup automated docker builds we need to link github with dockerhub to trigger the docker builds.   After approving this PR, someone will need to login to dockerhub as postgraphql and

In DockerHub logged in as postgraphql
1. Click on the profile drop down (upper right corner)
1. Choose Settings
1. Click on Linked Accounts and Services
1. Click on Link GItHub
1. Choose either of the linking options 

In GIthub logged in as postgraphql 
1.  Go to the repo settings
1.  Click on Integrations and Services
1.  Click on Add Service and find 'Docker'
1.  Click Add Service

Then I can delete and re-setup the automated docker build and make it public or I can send more instructions.

### CODE REVIEW

**Comment by benjie** [comment]
Failing, not your fault, because:

```
npm ERR! peerinvalid The package graphql@0.10.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer graphiql@0.9.1 wants graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0
```

This probably affects master too.

**Comment by benjie** [comment]
Thanks for doing this, @angelosarto, I'll get back to you in the next week. If I don't, please feel free to give me a nudge.

**Comment by benjie** [comment]
Hi @angelosarto; I've now completed the above instructions - back to you. Are you happy being in charge of Docker for this project?

**Comment by angelosarto** [comment]
@benjie sounds good. I will maintain the dockerhub.  I will login today and make it public and make sure the builds can be pulled publicly.

**Comment by benjie** [comment]
Awesome, thanks!

**Comment by angelosarto** [comment]
@benjie I think you linked the docker account to your github account -- so when I build from docker it is grabbing benjie/postgraphql   Could you delete the github link and link it to postgraphql git account instead so it points at postgraphql/postgraphql?

**Comment by benjie** [comment]
The PostGraphQL GitHub "account" is an organization - I don't think you can log in as it to Docker hub?

I added the Docker integration to `postgraphql/postgraphql`; I'm not sure why it would be looking at `benjie/postgraphql`?

**Comment by angelosarto** [comment]
@benjie Sorry for the delay -- had an issue with a production deployment at the day-job that consumed a bunch of time.   I am just checking back into this now.

In Github can you check under "settings" the "Authorized OAuth Apps" section then click on the name "Docker Hub Registry"  there should be a heading for "Organization access"  and if not yet granted to the postgraphql organization there should be a "Grant button"

**Comment by benjie** [comment]
@angelosarto Great; done - let me know if it worked 👍

**Comment by benjie** [comment]
(I had to use a different GitHub account because some old clients do not have Third Party app security enabled and I don't want to grant access to their repos - I don't think this should cause you any problems but just letting you know.)

**Comment by angelosarto** [comment]
@benjie Perfect - the docker images are all up and working!   I should have some time to submit new docs to the doc site for running docker versions of postgraphql

**Comment by benjie** [comment]
Awesome, thanks @angelosarto!

**Comment by meglio** [comment]
Is a Docker image planned for Graphile (= graphql v4)?

Also, an example using with docker-compose and combining with PostgreSQL docker image would be very useful. Should I create a separate issue asking about usage in docker-compose?

**Comment by benjie** [comment]
Open another issue 👍

This may help: https://github.com/postgraphql/postgraphql/issues/636#issuecomment-346960352

**Comment by angelosarto** [comment]
@meglio 
replying to this old comment -- I think with postgraphile supporting npx and aws lambda. I am not sure that there will be much of a use case for docker image.  npx takes care of quick and dirty local and running direct in a lambda takes care of a lot as well.

If I am wrong - I think adding it to graphile should be pretty trivial - its near the same dockerfile.

**Pull request merged**
