### PR TITLE
Clarify the expected value of `jwtRole`

### PR DESCRIPTION
**Pull request by bradleyayers**

### CODE REVIEW

**Comment by benjie** [comment]
Weird CI issue :(

**Comment by chadfurman** [comment]
@benjie CI doesn't run automatically when a PR is opened, does it?  If so, that's very dangerous.  If not, good for you!  :)

**Comment by benjie** [comment]
Yes it does, but CI doesn't have access to anything dangerous (e.g. it doesn't publish to npm/etc, so doesn't have any secrets in its envvars or similar). I'm not aware of any security issues with doing so, but if we were to auto-publish to npm or similar then I'd certainly lock it down! If you have evidence of it being dangerous configured how it is currently please let me know so I can disable it.

**Comment by benjie** [comment]
So I think the CI issue is that something's updated and UglifyJs can't handle `=>` arrow function syntax. v4 has a yarn.lock preventing this being an issue but v3 doesn't.

**Comment by chadfurman** [comment]
w.r.t. security, a compromised CI server (if it builds _anything_) could backdoor the builds.  That said, if the CI server is read-only and only runs the tests, the wors that could happen is that the CI server is zombified and used to perform malicious acts against others.

**Pull request merged**
